export const SELECT_CHAT = 'SELECT_CHAT';
export const OPEN_CHAT = 'OPEN_CHAT';
export const UPDATE_CHAT_INFO = 'UPDATE_CHAT_INFO';

export const CLOSE_NEW_CHAT_MODAL = 'CLOSE_NEW_CHAT_MODAL';
export const CLOSE_CHAT_SETTINGS_MODAL = 'CLOSE_CHAT_SETTINGS_MODAL';

export const CREATE_NEW_CHAT = 'CREATE_NEW_CHAT';
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT';

export const ADD_MEMBERS = 'ADD_MEMBERS';
export const UPDATE_MEMBERS = 'UPDATE_MEMBERS';

export const CLEAR_SELECT_MESSAGE = 'CLEAR_SELECT_MESSAGE';
export const UPDATE_CHAT_MESSAGE = 'UPDATE_CHAT_MESSAGE';
export const SHOW_CHAT_ICON = 'HIDE_CHAT_ICON';
