export const SELECT_CHAT = 'SELECT_CHAT';
export const OPEN_CHAT = 'OPEN_CHAT';
export const UPDATE_CHAT_INFO = 'UPDATE_CHAT_INFO';
export const ADD_MEMBERS = 'ADD_MEMBERS';
export const CLOSE_NEW_CHAT_MODAL = 'CLOSE_NEW_CHAT_MODAL';

export const CREATE_NEW_DIALOG = 'CREATE_NEW_DIALOG';
export const CREATE_NEW_CHAT = 'CREATE_NEW_CHAT';

export const CLEAR_SELECT_MESSAGE = 'CLEAR_SELECT_MESSAGE';
